"""Export world land and the Chinese-view outline to local SVG masks.

World: ne_110m_admin_0_countries.geojson, natural-earth-vector commit
ca96624a56bd078437bca8184e78163e5039ad19.
License: https://www.naturalearthdata.com/about/terms-of-use/
China: https://geo.datav.aliyun.com/areas_v3/bound/100000.json
Reference: https://dnr.yn.gov.cn/html/2023/mtbd_0828/42854.html
Keep all 277 outline components, including islands and maritime indicators.
This illustrative export is not an officially reviewed standard map.
"""

import argparse
import hashlib
import json
import math
from pathlib import Path


WEST = -30


def clip_ring(ring, boundary, keep_right):
    result = []
    previous = ring[-1]
    for current in ring:
        previous_inside = previous[0] >= boundary if keep_right else previous[0] <= boundary
        current_inside = current[0] >= boundary if keep_right else current[0] <= boundary
        if previous_inside != current_inside:
            ratio = (boundary - previous[0]) / (current[0] - previous[0])
            result.append([boundary, previous[1] + ratio * (current[1] - previous[1])])
        if current_inside:
            result.append(current)
        previous = current
    return result


def geometry_path(geometry):
    polygons = geometry["coordinates"]
    if geometry["type"] == "Polygon":
        polygons = [polygons]
    elif geometry["type"] != "MultiPolygon":
        raise ValueError(f"Unsupported geometry: {geometry['type']}")
    rings = []
    for polygon in polygons:
        for source_ring in polygon:
            if any(not math.isfinite(value) for point in source_ring for value in point):
                raise ValueError("Invalid geographic coordinate")
            # Clip both sides of the new seam instead of drawing wraparound chords.
            for shift in (-360, 0, 360):
                ring = [[lon + shift, lat] for lon, lat in source_ring]
                ring = clip_ring(ring, WEST, True)
                if ring:
                    ring = clip_ring(ring, WEST + 360, False)
                if len(ring) < 3:
                    continue
                points = []
                for lon, lat in ring:
                    if not -90 <= lat <= 90:
                        raise ValueError("Invalid latitude")
                    points.append(f"{(lon - WEST) / 360 * 1000:.4f},{(90 - lat) / 180 * 500:.4f}")
                rings.append("M" + "L".join(points) + "Z")
    return "".join(rings)


def export(source, china_source):
    data = json.loads(source.read_text())
    china_bytes = china_source.read_bytes()
    if hashlib.sha256(china_bytes).hexdigest() != "83ac502aeac66a5527607ec844169418505d990f1a2dc33226743643541eed3c":
        raise ValueError("China source changed; review its full geographic coverage before updating the hash")
    china_data = json.loads(china_bytes)
    feature, = china_data["features"]
    if feature["properties"]["adcode"] != 100000 or len(feature["geometry"]["coordinates"]) != 277:
        raise ValueError("Expected the complete pinned Chinese outline")
    world = [geometry_path(feature["geometry"]) for feature in data["features"]]
    china = [geometry_path(feature["geometry"])]
    if not world:
        raise ValueError("Expected world geometry")
    root = Path(__file__).resolve().parents[1] / "art"
    for name, paths in (("atlas-world", world), ("atlas-china", china)):
        drawing = "\n".join(f'<path fill-rule="evenodd" d="{path}"/>' for path in paths)
        (root / f"{name}.svg").write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 500" fill="white">\n'
            f'<!-- {"Natural Earth, public domain" if name == "atlas-world" else "DataV.GeoAtlas, Chinese-view outline"}. Generated by scripts/export_atlas.py. -->\n'
            + drawing + "\n</svg>\n"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Pinned Natural Earth world GeoJSON")
    parser.add_argument("china_source", type=Path, help="Pinned DataV China outline GeoJSON")
    args = parser.parse_args()
    export(args.source, args.china_source)
