"""Export public-domain Natural Earth 1:110m geometry to local SVG masks.

Input: ne_110m_admin_0_countries.geojson from natural-earth-vector commit
ca96624a56bd078437bca8184e78163e5039ad19.
Source: https://github.com/nvkelso/natural-earth-vector
License: https://www.naturalearthdata.com/about/terms-of-use/
"""

import argparse
import json
import math
from pathlib import Path


def geometry_path(geometry):
    polygons = geometry["coordinates"]
    if geometry["type"] == "Polygon":
        polygons = [polygons]
    elif geometry["type"] != "MultiPolygon":
        raise ValueError(f"Unsupported geometry: {geometry['type']}")
    rings = []
    for polygon in polygons:
        for ring in polygon:
            points = []
            for lon, lat in ring:
                if not math.isfinite(lon) or not math.isfinite(lat):
                    raise ValueError("Invalid geographic coordinate")
                points.append(f"{(lon + 180) / 360 * 1000:.1f},{(90 - lat) / 180 * 500:.1f}")
            rings.append("M" + "L".join(points) + "Z")
    return "".join(rings)


def export(source):
    data = json.loads(source.read_text())
    world = []
    china = []
    for feature in data["features"]:
        path = geometry_path(feature["geometry"])
        world.append(path)
        if feature["properties"]["ADM0_A3"] == "CHN":
            china.append(path)
    if not world or len(china) != 1:
        raise ValueError("Expected world geometry and one China feature")
    root = Path(__file__).resolve().parents[1] / "art"
    for name, paths in (("atlas-world", world), ("atlas-china", china)):
        drawing = "\n".join(f'<path fill-rule="evenodd" d="{path}"/>' for path in paths)
        (root / f"{name}.svg").write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 500" fill="white">\n'
            '<!-- Natural Earth, public domain. Generated by scripts/export_atlas.py. -->\n'
            + drawing + "\n</svg>\n"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="Pinned Natural Earth GeoJSON")
    export(parser.parse_args().source)
