"""Derive the animated water surface from the pond's original SVG geometry."""

from copy import deepcopy
from pathlib import Path
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)


def tag(name):
    return f"{{{NS}}}{name}"


def main():
    source = ET.parse(ROOT / "art" / "pond-garden.svg").getroot()
    definitions = source.find(tag("defs"))
    if definitions is None:
        raise ValueError("The pond SVG must contain its source definitions.")
    root = ET.Element(tag("svg"), {
        "width": "1500", "height": "760", "viewBox": "0 0 1500 760",
    })
    ET.SubElement(root, tag("title")).text = "Painted pond water excluding the foreground plants"
    defs = deepcopy(definitions)
    root.append(defs)
    silhouette = ET.SubElement(defs, tag("filter"), {
        "id": "pond-effect-silhouette", "x": "-10%", "y": "-10%",
        "width": "120%", "height": "120%",
    })
    ET.SubElement(silhouette, tag("feColorMatrix"), {
        "type": "matrix",
        "values": "0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0",
    })
    transfer = ET.SubElement(silhouette, tag("feComponentTransfer"))
    ET.SubElement(transfer, tag("feFuncA"), {
        "type": "discrete", "tableValues": "0 " + " ".join(["1"] * 31),
    })
    ET.SubElement(silhouette, tag("feMorphology"), {"operator": "dilate", "radius": "2"})
    mask = ET.SubElement(defs, tag("mask"), {
        "id": "pond-effect-water", "maskUnits": "userSpaceOnUse",
        "x": "0", "y": "0", "width": "1500", "height": "760",
    })
    surface = ET.SubElement(mask, tag("g"), {"mask": "url(#pond-edge)"})
    ET.SubElement(surface, tag("use"), {
        "href": "#pond-pool-shape", "fill": "white", "filter": "url(#pond-soft)",
    })
    plants = ET.SubElement(mask, tag("g"), {"filter": "url(#pond-effect-silhouette)"})
    for identifier in ["pond-back-reeds", "pond-bank-plants", "pond-back-lilies", "pond-front-lilies"]:
        group = source.find(f".//*[@id='{identifier}']")
        if group is None:
            raise ValueError(f"Missing pond foreground group: {identifier}")
        plants.append(deepcopy(group))
    ET.SubElement(root, tag("rect"), {
        "width": "1500", "height": "760", "fill": "white", "mask": "url(#pond-effect-water)",
    })
    ET.indent(root, space="  ")
    (ROOT / "art" / "pond-water-mask.svg").write_text(
        "<!-- Generated by scripts/export_pond_mask.py; edit pond-garden.svg. -->\n"
        + ET.tostring(root, encoding="unicode") + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
