"""Derive animation layers from the original SVG, retaining its pigment and veins."""

from copy import deepcopy
from pathlib import Path
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)


def tag(name):
    return f"{{{NS}}}{name}"


def write_svg(root, name):
    ET.indent(root, space="  ")
    content = ET.tostring(root, encoding="unicode")
    (ROOT / "art" / name).write_text(
        "<!-- Generated by scripts/export_fern_art.py; edit woodland-ferns.svg. -->\n"
        + content + "\n",
        encoding="utf-8",
    )


def main():
    root = ET.parse(ROOT / "art" / "woodland-ferns.svg").getroot()
    defs = root.find(tag("defs"))
    if defs is None:
        raise ValueError("The woodland SVG must contain its source definitions.")

    atlas = ET.Element(tag("svg"), {
        "width": "1056", "height": "184", "viewBox": "0 0 528 92", "fill": "none",
    })
    ET.SubElement(atlas, tag("title")).text = "Source watercolor fern leaflets"
    atlas.append(deepcopy(defs))
    for index, variant in enumerate(["woodland-pinna", "woodland-pinna-deep", "woodland-pinna-pale"]):
        group = ET.SubElement(atlas, tag("g"), {"transform": f"translate({index * 176 + 12} 68)"})
        ET.SubElement(group, tag("use"), {"href": f"#{variant}"})
    write_svg(atlas, "fern-leaf-atlas.svg")


if __name__ == "__main__":
    main()
